### ISSUE TITLE
Changing config.py file

### ISSUE THREAD

**Issue by amsinha9** [razeineldin/DeepSeg#2]
Great work! What is the difference between the following below:

config['preprocessed_brats'] = '/PATH/TO/BraTS19_train_preprocessed/'
config['preprocessed_brats_imgs'] = '/PATH/TO/BraTS19_train_images/'

and this:

config['dataset_path'] = '/PATH/TO/dataset_brats19/' # path to the dataset containing 2d images

**Comment by razeineldin** [comment]
Thanks for your interest in DeeSeg!

According to the preprocessing step in [README file](https://github.com/razeineldin/DeepSeg/blob/master/README.md):
The original BRATS dataset path is stored in **_config['brats_path']_**.
Then, it is preprocessed using [preprocess.py](https://github.com/razeineldin/DeepSeg/blob/master/preprocess.py) and the output is stored in **_config['preprocessed_brats']_**.
After that, the preprocessed output is converted into 2D images using [preprocess_2d_images.py](https://github.com/razeineldin/DeepSeg/blob/master/preprocess_2d_images.py) and the result is stored in **_config['preprocessed_brats_imgs']_**.
Finally, all 2D images should be placed in 2D dataset folder (specified by **_config['dataset_path']_**) according to the following structure: 
``` dataset_brats19/
├── train_images
│   └── image_FLAIR
├── train_segmentation
│   ├── truth
│   └── truth_complete
├── val_images
│   └── image_FLAIR
└── val_segmentation
    ├── truth
    └── truth_complete
```

I hope this makes it clearer.

**Comment by amsinha9** [comment]
Thanks for the response. So, does config['brats_path'] = '/PATH/TO/MICCAI_BraTS_2019_Data_Training/' correspond to a directory with folders for each subject that have their corresponding FLAIR, T1, T1ce, and T2 including the segmentation nifti file, or do the label files go elsewhere? 

It's just a little unclear if we specify different locations for the training data vs the ground truth segmentation labels in the config file. Or we do make a specific directory called 'train_segmentation' to put the labeled data in? 

Overall, could you just clarify which lines need to be changed in the config.py file specifically for the paths in order to get the same results you did?

This is a great model that I'd like to work with, so hope to hear from you soon!

**Comment by razeineldin** [comment]
Sorry for my late reply.

As you already said, **_config['brats_path']_** refers to the 'MICCAI_BraTS_2019_Data_Training' folder which is included in the BraTS 2019 by default and it contains two folders, namely, HGG and LGG each contains all MRI nifti files as well as the segmentation. No further editing or arranging of files is needed.

You don't have to create any folder for the output of the preprocessing stage. Instead, you should only specify the saving paths for the output using **_config['preprocessed_brats']_** and **_config['preprocessed_brats_imgs']_**  and the folders specified by will be created after running preprocess.py and  preprocess_2d_images.py, respectively. 

Then, you should only create a dataset folder following the above structure and copy all resultant 2d images from **_config['preprocessed_brats_imgs']_** to the folder specified by config['dataset_path']) according to the above structure. 

It seems a little complicated, but you should do it only once.

More clarification was included in the [config.py file](https://github.com/razeineldin/DeepSeg/blob/master/config.py).

**Comment by razeineldin** [comment]
Sorry for my late reply.

As you already said, **_config['brats_path']_** refers to the 'MICCAI_BraTS_2019_Data_Training' folder which is included in the BraTS 2019 by default and it contains two folders, namely, HGG and LGG each contains all MRI nifti files as well as the segmentation. No further editing or arranging of files is needed.

Then, you should specify the saving paths for the output using **_config['preprocessed_brats']_** and **_config['preprocessed_brats_imgs']_**  and the folders specified by will be created after running preprocess.py and  preprocess_2d_images.py, respectively.

After that after running **_config['preprocessed_brats']_**, you should manually divide the processed data into folders for different mri modalities (t1, t1ce, flair, t2) as following:
``` BraTS19_train_preprocessed/
├── image_FLAIR
├── image_t1
├── image_t1ce
├── image_t2
└── truth
```
Finally, you should create a dataset folder and copy all resultant 2d images from **_config['preprocessed_brats_imgs']_** to the folder specified by config['dataset_path']) according to the following structure: 

``` dataset_brats19/
├── train_images
│   └── image_FLAIR
├── train_segmentation
│   ├── truth
│   └── truth_complete
├── val_images
│   └── image_FLAIR
└── val_segmentation
    ├── truth
    └── truth_complete
```
It seems a little complicated, but you should do it only once.

More clarification was included in the [config.py file](https://github.com/razeineldin/DeepSeg/blob/master/config.py). [Sample folders](https://github.com/razeineldin/DeepSeg/blob/master/sample_brats19_folders.zip) were uploaded for more illustration.

Please refer to the [README.md](https://github.com/razeineldin/DeepSeg/blob/master/README.md) for more detail about the used steps.

**Comment by amsinha9** [comment]
This was extremely helpful! Thanks for adding in the zip file as a reference. This may be more of a Python-specific thing, but after editing config.py accordingly, when I try to run preprocess.py, I get the following:

line 143, in <module> os.mkdir(config['log_dir'])
PermissionError: [Errno 13] Permission denied: 'logs'

Any idea how I could resolve this?

**Comment by razeineldin** [comment]
Great!

Could you specify which OS are you using?

It seems to be a permission error. So, running the script as administrator may solve the problem.

**Comment by amsinha9** [comment]
Yes, I'm using Linux. I'll try to run preprocess.py as sudo.

**Comment by razeineldin** [comment]
It should work fine if your user has enough permissions. Otherwise, sudo should resolve this issue.

Best

**Comment by freshnemo** [comment]
What is the difference between truth and truth_complete in segmentation folder?

**Comment by razeineldin** [comment]
Hello @freshnemo,

The truth folder include ground truth segmentations of all labels:
1. Enhancing tumor (ET — label 4)
2. Edema (ED — label 2), 
3. and necrotic and non-enhancing tumor core (NCR/NET — label 1).

While in truth_complete, all labels are converted into label 1 so that the segmentation images represent only the whole tumor region.
