### ISSUE TITLE
How to obtain the images of "val_segmentation" folders?

### ISSUE THREAD

**Issue by SabirKhanAkash** [razeineldin/DeepSeg#3]
**what is the difference between train_images and val images and from where will I get the val_segmentation of the dataset folder ? and after that which files should I execute and is there any necessity of modification or not? It will be very much helpful for me if you kindly tell me which versions of the python libraries did you use in this work.** 
@razeineldin please answer, sir.

**Comment by SabirKhanAkash** [comment]
Update: All I had to do is to split the truth images into train and validation directory using python's **splitfolders** library.

**Comment by razeineldin** [comment]
@SabirKhanAkash, I'm so sorry for replying very late.

Great that you found a solution to your question. The data should be divided into a split of train:valid with a ratio of 80:20 %. The was originally using a bash script, but can be done with other libraries like split-folders (as you mentioned), or [keras ](https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html).

This repository was implemented on Ubuntu 18.04 machine with Python 3.6, Keras 2.2.

Best.
