### ISSUE TITLE
What is the different between the two files truth and truth_complete?

### ISSUE THREAD

**Issue by kszuyen** [razeineldin/DeepSeg#5]

**Comment by razeineldin** [comment]
Hello kszuyen,

Thank you for your interest in DeepSeg. 

Truth is the ground truth annotation provided by the BraTS Challenge (including all tumor labels l1, l2, l4), while Truth_complete is the whole tumor region (i.e. all tumor labels are converted into label 1).

Good luck! 

Best regards,
Ramy

**Comment by kszuyen** [comment]
Hello, so I am recently reading your paper DeepSeg, and trying to implement your code again on my own. Maybe because I’m a beginner in deep learning with images, I encountered some problems, and I really hope you could reply.I’m now in the step to preprocess 2D images.

The first question is that the preprocess to 2D make 155 images for each case into a single file. Do you use all of these images to train your model? Or how to choose which image to train the model for each case?
Second is that for the label(segmentation or truth) images, am I comprehending it right that for the tumor region you assign it to 1, and for the others you assign it to 0? Because when I visualize the images I can only see black. I’m not sure if I am on the right track.

Sorry for bothering you with these basic or simple questions, but it’ll mean a lot to me if you could reply.

**Comment by razeineldin** [comment]
Hi @kszuyen,

Thanks for your questions. 

Firstly, the training of DeepSeg took only the images with tumor into consideration. This is one of tge strategies we followed to compensate for the data imbalance problem. 

Secondly, you are right, 1 for the tumor segmentation while 0 for the background.

Good luck!
